services:
  postgres:
    image: postgres:17
    container_name: stickyboard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - sticky_pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d   # auto-seed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sticky_net
    ports:
      - "5432:5432"  # kept open for dev convenience; can remove in prod

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: stickyboard_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST:-postgres}:5432/${POSTGRES_DB}

    volumes:
      - ./logs/api:/app/logs
    ports:
      - "8080:8080"         # open in dev, proxied in prod
    restart: unless-stopped
    networks:
      - sticky_net

  # worker:
  #   build: ./worker
  #   container_name: stickyboard_worker
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #   volumes:
  #     - ./worker:/app
  #   restart: unless-stopped
  #   networks:
  #     - sticky_net

networks:
  sticky_net:
    driver: bridge

volumes:
  sticky_pgdata:
